version: "3.3"

services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER:     ${DB_USER}
            POSTGRES_DB:       ${DB_NAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./db_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
    adminer:
        image: adminer
        depends_on: 
            - "db"
        ports:
            - 8081:8080